// <auto-generated />
using System;
using KentKart.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KentKart.Api.Migrations
{
    [DbContext(typeof(KentKartDbContext))]
    partial class KentKartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KentKart.Api.Entities.BusLine", b =>
                {
                    b.Property<int>("BusLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusLineId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BusLineId");

                    b.HasIndex("LineCode")
                        .IsUnique();

                    b.ToTable("BusLines");

                    b.HasData(
                        new
                        {
                            BusLineId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Umuttepe kampüsü ile İzmit Otogar arası hat",
                            IsActive = true,
                            LineCode = "41K",
                            LineName = "Umuttepe - İzmit Otogar"
                        },
                        new
                        {
                            BusLineId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İzmit ve Gebze arası şehir içi ulaşım hattı",
                            IsActive = true,
                            LineCode = "200",
                            LineName = "İzmit - Gebze"
                        },
                        new
                        {
                            BusLineId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Körfez ve İzmit merkezi arası hat",
                            IsActive = true,
                            LineCode = "145",
                            LineName = "Körfez - İzmit"
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("CardTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Cards", t =>
                        {
                            t.HasCheckConstraint("CK_Cards_Balance", "[Balance] >= 0");

                            t.HasCheckConstraint("CK_Cards_Status", "[Status] IN ('Active', 'Passive', 'Lost')");
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.CardApplication", b =>
                {
                    b.Property<int>("CardApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardApplicationId"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CardApplicationId");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("CardApplications", t =>
                        {
                            t.HasCheckConstraint("CK_CardApplications_Status", "[Status] IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.CardType", b =>
                {
                    b.Property<int>("CardTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DiscountRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CardTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CardTypes", t =>
                        {
                            t.HasCheckConstraint("CK_CardTypes_DiscountRate", "[DiscountRate] >= 0 AND [DiscountRate] <= 100");
                        });

                    b.HasData(
                        new
                        {
                            CardTypeId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Standart tam ücretli kart",
                            DiscountRate = 0m,
                            IsActive = true,
                            Name = "Tam Kart"
                        },
                        new
                        {
                            CardTypeId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Öğrenciler için indirimli kart",
                            DiscountRate = 50m,
                            IsActive = true,
                            Name = "Ogrenci Kart"
                        },
                        new
                        {
                            CardTypeId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Belirli kullanıcılar için indirimli kart",
                            DiscountRate = 30m,
                            IsActive = true,
                            Name = "Indirimli Kart"
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.FareRule", b =>
                {
                    b.Property<int>("FareRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FareRuleId"));

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("FareRuleId");

                    b.HasIndex("CardTypeId");

                    b.ToTable("FareRules", t =>
                        {
                            t.HasCheckConstraint("CK_FareRules_DateRange", "[ValidTo] IS NULL OR [ValidTo] >= [ValidFrom]");

                            t.HasCheckConstraint("CK_FareRules_Price", "[Price] > 0");
                        });

                    b.HasData(
                        new
                        {
                            FareRuleId = 1,
                            CardTypeId = 1,
                            IsActive = true,
                            Price = 20m,
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FareRuleId = 2,
                            CardTypeId = 2,
                            IsActive = true,
                            Price = 10m,
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FareRuleId = 3,
                            CardTypeId = 3,
                            IsActive = true,
                            Price = 14m,
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.LineStation", b =>
                {
                    b.Property<int>("LineStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineStationId"));

                    b.Property<int>("BusLineId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("StationOrder")
                        .HasColumnType("int");

                    b.HasKey("LineStationId");

                    b.HasIndex("StationId");

                    b.HasIndex("BusLineId", "StationId")
                        .IsUnique();

                    b.HasIndex("BusLineId", "StationOrder")
                        .IsUnique();

                    b.ToTable("LineStations", t =>
                        {
                            t.HasCheckConstraint("CK_LineStations_StationOrder", "[StationOrder] > 0");
                        });

                    b.HasData(
                        new
                        {
                            LineStationId = 1,
                            BusLineId = 1,
                            StationId = 1,
                            StationOrder = 1
                        },
                        new
                        {
                            LineStationId = 2,
                            BusLineId = 1,
                            StationId = 2,
                            StationOrder = 2
                        },
                        new
                        {
                            LineStationId = 3,
                            BusLineId = 1,
                            StationId = 3,
                            StationOrder = 3
                        },
                        new
                        {
                            LineStationId = 4,
                            BusLineId = 1,
                            StationId = 4,
                            StationOrder = 4
                        },
                        new
                        {
                            LineStationId = 5,
                            BusLineId = 2,
                            StationId = 4,
                            StationOrder = 1
                        },
                        new
                        {
                            LineStationId = 6,
                            BusLineId = 2,
                            StationId = 5,
                            StationOrder = 2
                        },
                        new
                        {
                            LineStationId = 7,
                            BusLineId = 3,
                            StationId = 6,
                            StationOrder = 1
                        },
                        new
                        {
                            LineStationId = 8,
                            BusLineId = 3,
                            StationId = 3,
                            StationOrder = 2
                        },
                        new
                        {
                            LineStationId = 9,
                            BusLineId = 3,
                            StationId = 4,
                            StationOrder = 3
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("BalanceLoad");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Success");

                    b.HasKey("PaymentId");

                    b.HasIndex("CardId");

                    b.HasIndex("PaymentDate");

                    b.ToTable("Payments", t =>
                        {
                            t.HasTrigger("trg_AfterPaymentInsert_UpdateCardBalance");

                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_Method", "[PaymentMethod] IN ('CreditCard', 'DebitCard', 'BankTransfer')");

                            t.HasCheckConstraint("CK_Payments_Status", "[Status] IN ('Success', 'Failed', 'Cancelled')");

                            t.HasCheckConstraint("CK_Payments_Type", "[PaymentType] IN ('BalanceLoad', 'Subscription')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KentKart.Api.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sistem yöneticisi",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Normal kullanıcı",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StationId");

                    b.HasIndex("StationName");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "İzmit",
                            IsActive = true,
                            StationName = "Umuttepe Kampüs"
                        },
                        new
                        {
                            StationId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "İzmit",
                            IsActive = true,
                            StationName = "Yahya Kaptan"
                        },
                        new
                        {
                            StationId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "İzmit",
                            IsActive = true,
                            StationName = "Anıtpark"
                        },
                        new
                        {
                            StationId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "İzmit",
                            IsActive = true,
                            StationName = "İzmit Otogar"
                        },
                        new
                        {
                            StationId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Gebze",
                            IsActive = true,
                            StationName = "Gebze Merkez"
                        },
                        new
                        {
                            StationId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Körfez",
                            IsActive = true,
                            StationName = "Körfez Merkez"
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("BusLineId")
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Completed");

                    b.Property<DateTime>("TripDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("TripId");

                    b.HasIndex("CardId");

                    b.HasIndex("StationId");

                    b.HasIndex("TripDate");

                    b.HasIndex("BusLineId", "TripDate");

                    b.ToTable("Trips", t =>
                        {
                            t.HasCheckConstraint("CK_Trips_FareAmount", "[FareAmount] >= 0");

                            t.HasCheckConstraint("CK_Trips_Status", "[Status] IN ('Completed', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("KentKart.Api.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KentKart.Api.Entities.Card", b =>
                {
                    b.HasOne("KentKart.Api.Entities.CardType", "CardType")
                        .WithMany("Cards")
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KentKart.Api.Entities.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KentKart.Api.Entities.CardApplication", b =>
                {
                    b.HasOne("KentKart.Api.Entities.CardType", "CardType")
                        .WithMany("CardApplications")
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KentKart.Api.Entities.User", "User")
                        .WithMany("CardApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KentKart.Api.Entities.FareRule", b =>
                {
                    b.HasOne("KentKart.Api.Entities.CardType", "CardType")
                        .WithMany("FareRules")
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardType");
                });

            modelBuilder.Entity("KentKart.Api.Entities.LineStation", b =>
                {
                    b.HasOne("KentKart.Api.Entities.BusLine", "BusLine")
                        .WithMany("LineStations")
                        .HasForeignKey("BusLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KentKart.Api.Entities.Station", "Station")
                        .WithMany("LineStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusLine");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("KentKart.Api.Entities.Payment", b =>
                {
                    b.HasOne("KentKart.Api.Entities.Card", "Card")
                        .WithMany("Payments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("KentKart.Api.Entities.Trip", b =>
                {
                    b.HasOne("KentKart.Api.Entities.BusLine", "BusLine")
                        .WithMany("Trips")
                        .HasForeignKey("BusLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KentKart.Api.Entities.Card", "Card")
                        .WithMany("Trips")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KentKart.Api.Entities.Station", "Station")
                        .WithMany("Trips")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusLine");

                    b.Navigation("Card");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("KentKart.Api.Entities.User", b =>
                {
                    b.HasOne("KentKart.Api.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KentKart.Api.Entities.BusLine", b =>
                {
                    b.Navigation("LineStations");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("KentKart.Api.Entities.Card", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("KentKart.Api.Entities.CardType", b =>
                {
                    b.Navigation("CardApplications");

                    b.Navigation("Cards");

                    b.Navigation("FareRules");
                });

            modelBuilder.Entity("KentKart.Api.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KentKart.Api.Entities.Station", b =>
                {
                    b.Navigation("LineStations");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("KentKart.Api.Entities.User", b =>
                {
                    b.Navigation("CardApplications");

                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
